apiVersion: v1
kind: Pod
metadata:
  name: mft-pod-uno
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: rdmashared-net
spec:
  hostNetwork: true
  serviceAccount: mfttool
  containers:
    - name: mft-container-uno
      image: quay.io/redhat_emp1/ecosys-nvidia/mfttools:1.0.1
      securityContext:
        privileged: true
      #image: quay.io/jschless/gpu-tools:0.0.6 
      #image: quay.io/redhat_emp1/ecosys-nvidia/gpu-tools:0.0.3 
      resources:
        requests:
          nvidia.com/gpu: 4
          rdma/rdma_shared_device_eth: 1
        limits:
          nvidia.com/gpu: 4
          rdma/rdma_shared_device_eth: 1

