apiVersion: v1
kind: Pod
metadata:
  name: sriovlegacy-workload-uno
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-network
spec:
  nodeSelector: 
    kubernetes.io/hostname: mocr4pcc02u31  
#    kubernetes.io/hostname: nvd-srv-32.nvidia.eng.rdu2.dc.redhat.com
  serviceAccountName: rdma
  containers:
  - image: quay.io/jschless/gpu-tools:0.0.6 
#  - image: quay.io/redhat_emp1/ecosys-nvidia/gpu-operator:tools
    name: sriovlegacy-workload-uno
#    command:
#      - sh
#      - -c
#      - sleep inf
    securityContext:
      privileged: true
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        nvidia.com/gpu: 4 
        openshift.io/sriovlegacy: 1
      requests:
        nvidia.com/gpu: 4
        openshift.io/sriovlegacy: 1

