apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-name-is-inigo-montoya
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem

