apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: cx7-eno5np0
  namespace: openshift-sriov-network-operator
spec:
  resourceName: cx7_eno5
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 10
  numVfs: 1
  mtu: 9000
  nicSelector:
    pfNames:
      - eno5np0
    vendor: "15b3"
    deviceID: "1021"
  deviceType: netdevice
  isRdma: true
  linkType: eth
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: cx7-eno6np0
  namespace: openshift-sriov-network-operator
spec:
  resourceName: cx7_eno6
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 10
  numVfs: 1
  mtu: 9000
  nicSelector:
    pfNames:
      - eno6np0
    vendor: "15b3"
    deviceID: "1021"
  deviceType: netdevice
  isRdma: true
  linkType: eth
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: cx7-eno7np0
  namespace: openshift-sriov-network-operator
spec:
  resourceName: cx7_eno7
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 10
  numVfs: 1
  mtu: 9000
  nicSelector:
    pfNames:
      - eno7np0
    vendor: "15b3"
    deviceID: "1021"
  deviceType: netdevice
  isRdma: true
  linkType: eth
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: cx7-eno8np0
  namespace: openshift-sriov-network-operator
spec:
  resourceName: cx7_eno8
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 10
  numVfs: 1
  mtu: 9000
  nicSelector:
    pfNames:
      - eno8np0
    vendor: "15b3"
    deviceID: "1021"
  deviceType: netdevice
  isRdma: true
  linkType: eth


